# Generated by Django 3.2.3 on 2022-05-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
