# Generated by Django 3.2.3 on 2022-06-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0005_auto_20220608_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advatisment',
            name='image_sandle_1',
        ),
        migrations.RemoveField(
            model_name='advatisment',
            name='image_sleeper_1',
        ),
    ]
