# Generated by Django 3.2.3 on 2022-06-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
