# Generated by Django 3.2.3 on 2022-06-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0009_auto_20220619_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_payment_id',
        ),
    ]
